---

- set_fact:
    mysql_config_file: /etc/mysql/my.cnf

- name: droits sur fichier de conf
  file: 
    path: "{{ mysql_config_file }}"
    mode: 0644

- name: suppression fichier de configuration syslog qui gêne le démarrage
  file: path=/etc/mysql/conf.d/mysqld_safe_syslog.cnf state=absent

- name: renommage key_buffer pour éviter un warning
  replace: >
    dest={{ mysql_config_file }}
    regexp='^key_buffer[ \t]*=[ \t]*(.*)$'
    replace='key_buffer_size = \1'

- name: renommage myisam_recover pour éviter un warning
  replace: >
    dest={{ mysql_config_file }}
    regexp='^myisam_recover[ \t]*=[ \t]*(.*)$'
    replace='myisam_recover_options = \1'

- name: création dossier temporaire MySQL
  file: path="{{ mysql_tmpdir }}" state=directory owner=mysql group=mysql mode=0755
    
- name: Ensure Mysql dirs exists and has ok rights
  file: path={{ item }} state=directory owner=mysql group=mysql 
  with_items: [ "{{ mysql_datadir }}", "{{ mysql_logdir }}", "{{ mysql_replogdir }}" ]

#obsolète?, et plante mariadb sur debian 9
#- name: Configure datadir in global MySQL configuration
#  lineinfile: >
#    dest={{ mysql_config_file }}
#    regexp="^datadir"
#    line="datadir = {{ mysql_datadir }}"
#  when: mysql_datadir is defined

- name: le datadir par défaut est-il encore présent
  stat: path=/var/lib/mysql
  register: old_datadir 

- name: copie des données de /var/lib/mysql vers le nouveau datadir
  shell: cp -par /var/lib/mysql/* {{ mysql_datadir }}/
  when: old_datadir.stat.exists == True

- stat:
    path: /etc/apparmor.d/
  register: apparmor_installed

- name: "Reconfigure Apparmor to use new {{ mysql_mysqld_datadir }} and {{ mysql_logdir }} if they differ from standard"
  shell: "sed -i {{ item }} -e 's#/var/lib/mysql#{{ mysql_mysqld_datadir }}#g' -e 's#/var/log/mysql#{{ mysql_logdir }}#g'"
  register: sedchangeconf
  changed_when: sedchangeconf.stdout != ""
  with_items: 
    - "/etc/apparmor.d/usr.sbin.mysqld"
  args:
    warn: false
  when: apparmor_installed.stat.isdir is defined and apparmor_installed.stat.isdir and mysql_mysqld_datadir != mysql_std_datadir and mysql_logdir != mysql_std_logdir

- name: logrotate configuration
  template: src=templates/logrotate.j2 dest=/etc/logrotate.d/mysql-server mode=0644 owner=root group=root

- name: suppression standard dirs
  file: path={{ item }} state=absent
  with_items: 
    - /var/lib/mysql
    - /var/log/mysql

- name: fichier template configuration
  set_fact: 
    templateconf: "configuration.cnf.j2"
  
- name: Install cnf override into include directory
  template: src="{{ templateconf }}"
            dest="{{ mysql_cfg_incdir }}/configuration.cnf"
            owner=0 group=mysql mode=0640

- name: Install cnf override for binlog into include directory
  template: src="binlog.cnf.j2"
            dest="{{ mysql_cfg_incdir }}/binlog.cnf"
            owner=0 group=mysql mode=0640
  when: mysql_binlog is defined and mysql_binlog

- name: création fichier de log pour débloquer lancement mysql
  file: path=/space/logmysql/mysql-error.log state=touch owner=mysql group=mysql

#sécurité, pour éviter qu'un process reste en activité et lock l'accès au dossier (rencontré lors du déploiement en preprod, avril 2016)
- name: kill mysqld
  shell: killall {{ item }}
  with_items : [ mysqld, mysqld_safe ]
  failed_when: false
  changed_when: false
  when: mysql_install_packages

- name: Ensure MySQL is started and not enabled on boot
  service: name={{ mysql_svc }} state=started enabled=no
  changed_when: false
