---
- name: When mysql_mysqld_default_storage_engine is 'myisam'
  set_fact:
    mysql_engine: 'myisam'
    mysql_mysqld_key_buffer_size: "{{ (mysql_server_memory | int / 2 - 2048)| int | abs }}"
    mysql_mysqld_innodb_buffer_pool_size: 8
    mysql_mysqld_innodb_log_file_size: 48
  when: mysql_mysqld_default_storage_engine == "myisam"

- name: When mysql_mysqld_default_storage_engine is 'innodb'
  set_fact:
    mysql_engine: 'innodb'
    mysql_mysqld_key_buffer_size: 32
    mysql_mysqld_innodb_buffer_pool_size: "{{ (mysql_server_memory | int - 2048) | int | abs }}"
    mysql_mysqld_innodb_log_file_size: 256
  when: mysql_mysqld_default_storage_engine == "innodb"

- name: When mysql_mysqld_default_storage_engine is 'mixte'
  set_fact:
    mysql_engine: 'innodb'
    mysql_mysqld_key_buffer_size: "{{ (mysql_server_memory | int / 4 - 2048) | int | abs }}"
    mysql_mysqld_innodb_buffer_pool_size: "{{ (mysql_server_memory | int / 4) | int | abs }}"
    mysql_mysqld_innodb_log_file_size: 256
  when: mysql_mysqld_default_storage_engine == "mixte"

- name: Template performances.cnf
  template: 
    src: performances.cnf.j2 
    dest: "{{ osvar_cfg_incdir }}/performances.cnf"
    owner: mysql 
    group: mysql
  register: out

- name: Delete innodb log files created by apt package when performances.cnf change
  file: path={{ item }} state=absent
  with_items : [ "{{ mysql_mysqld_datadir }}/ib_logfile0", "{{ mysql_mysqld_datadir }}/ib_logfile1" ]
  when: out.changed

- name: Restart mysql when performances.cnf change
  service: name={{ mysql_svc }} state=restarted sleep=5
  when: out.changed