---
- name: Template master-replication.cnf
  template: 
    src: master-replication.cnf.j2 
    dest: "{{ osvar_cfg_incdir }}/master-replication.cnf"
    owner: mysql 
    group: mysql
  register: master_repl
  when: mysql_master_replication

- name: Template slave-replication.cnf
  template: 
    src: slave-replication.cnf.j2 
    dest: "{{ osvar_cfg_incdir }}/slave-replication.cnf"
    owner: mysql 
    group: mysql
  register: slave_repl
  when: mysql_slave_replication

- name: Ensure replication user exists on master
  mysql_user:
    name: "{{ mysql_replication_user.name }}"
    host: "{{ mysql_replication_user.host | default('%') }}"
    password: "{{ mysql_replication_user.password }}"
    priv: "{{ mysql_replication_user.priv | default('*.*:REPLICATION SLAVE') }}"
    state: present
    login_host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
  when: mysql_master_replication and mysql_root_password and mysql_master_replication_user != ''

- name: Check slave replication status
  mysql_replication: mode=getslave
  ignore_errors: True
  register: slave_repl_status
  when: mysql_slave_replication or mysql_master_replication

- name: Check master replication status
  mysql_replication: mode=getmaster login_user=root login_password="{{ mysql_root_password }}"
  become: false
  delegate_to: "{{ mysql_replication_master_ssh }}"
  register: master
  when: >
    (slave_repl_status is failed or slave_repl_status.Is_Slave == false) and
    (mysql_slave_replication or mysql_master_replication)

- name: Configure replication on the slave
  mysql_replication:
    mode: changemaster
    master_host: "{{ mysql_replication_master }}"
    master_user: "{{ mysql_replication_user.name }}"
    master_password: "{{ mysql_replication_user.password }}"
    master_log_file: "{{ master.File }}"
    master_log_pos: "{{ master.Position }}"
  ignore_errors: True
  when: >
    (slave_repl_status is failed or slave_repl_status.Is_Slave == false) and
    (mysql_slave_replication or mysql_master_replication and mysql_master_replication_user != '')

- name: Start replication
  mysql_replication: mode=startslave
  when: >
    (slave_repl_status is failed or slave_repl_status.Is_Slave == false) and
    (mysql_slave_replication or mysql_master_replication)
